# Generated by Django 3.2.19 on 2023-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAndOfficeToAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.CharField(max_length=2300, null=True)),
                ('date_received', models.DateTimeField()),
                ('affair', models.CharField(max_length=2300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File2Return2dOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.CharField(max_length=2300, null=True)),
                ('guy', models.DateTimeField()),
                ('involved', models.CharField(max_length=2300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceCompliant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.CharField(max_length=2300, null=True)),
                ('date_received', models.DateTimeField()),
                ('complainants', models.CharField(max_length=2300, null=True)),
                ('defendants', models.CharField(max_length=2300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceSubmissionLGGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2300, null=True)),
                ('Id_card', models.CharField(max_length=2300, null=True)),
                ('appearance_num', models.CharField(max_length=2300, null=True)),
                ('act_num', models.CharField(max_length=2300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficViolationCompared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_events', models.DateTimeField()),
                ('date_received', models.DateTimeField()),
                ('involved', models.CharField(max_length=2300, null=True)),
                ('id_card', models.CharField(max_length=2300, null=True)),
                ('violation_code', models.CharField(max_length=2300, null=True)),
                ('res_procedure', models.CharField(max_length=2300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficViolationComparedMyColission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField()),
                ('involved', models.CharField(max_length=2300, null=True)),
                ('res_procedure', models.CharField(max_length=2300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrbanControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed', models.CharField(max_length=2300, null=True)),
                ('date_received', models.DateTimeField()),
                ('Involved_applicant', models.CharField(max_length=2300, null=True)),
                ('res_report', models.CharField(max_length=2300, null=True)),
            ],
        ),
    ]
