# Generated by Django 3.2.19 on 2023-08-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('InspecciónAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintandofficetoattend',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
        migrations.AlterField(
            model_name='file2return2doffice',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
        migrations.AlterField(
            model_name='policecompliant',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
        migrations.AlterField(
            model_name='policesubmissionlggs',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
        migrations.AlterField(
            model_name='trafficviolationcompared',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
        migrations.AlterField(
            model_name='trafficviolationcomparedmycolission',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
        migrations.AlterField(
            model_name='urbancontrol',
            name='assign_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent'),
        ),
    ]
