# Generated by Django 3.2.19 on 2023-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0002_auto_20230817_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintandofficetoattend',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file2return2doffice',
            name='guy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policecompliant',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficviolationcompared',
            name='date_events',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficviolationcompared',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficviolationcomparedmycolission',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urbancontrol',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
