# Generated by Django 3.2.19 on 2023-08-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0003_auto_20230822_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficviolationcompared',
            name='compare_number',
            field=models.CharField(max_length=2300, null=True),
        ),
    ]
