# Generated by Django 3.2.19 on 2023-09-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_user_position'),
        ('InspecciónAPI', '0004_trafficviolationcompared_compare_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspNotifify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1000)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('assign_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent')),
            ],
        ),
    ]
