# Generated by Django 3.2.19 on 2023-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0006_carnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='policesubmissionlggs',
            name='type_of_identification',
            field=models.CharField(max_length=2300, null=True),
        ),
    ]
