# Generated by Django 3.2.19 on 2023-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0009_auto_20230922_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadsignedpdf',
            old_name='pdf',
            new_name='pdf_file1',
        ),
        migrations.AddField(
            model_name='uploadsignedpdf',
            name='pdf_file2',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/SignedPDF/'),
        ),
    ]
