# Generated by Django 3.2.19 on 2023-09-25 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InspecciónAPI', '0010_auto_20230925_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsignedpdf',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
