# Generated by Django 3.2.19 on 2023-10-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0007_auto_20231014_1203'),
        ('InspecciónAPI', '0011_uploadsignedpdf_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(max_length=310)),
                ('selected_urban_control_ids', models.TextField()),
                ('selected_police_compliant_ids', models.TextField()),
                ('selected_policeSubmissionLGGS_ids', models.TextField()),
                ('selected_trafficViolationCompared_ids', models.TextField()),
                ('selected_trafficViolationComparedMyColission_ids', models.TextField()),
                ('selected_complaintAndOfficeToAttend_ids', models.TextField()),
                ('selected_file2Return2dOffice_ids', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assign_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.agent')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
