# Generated by Django 3.2.19 on 2023-10-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0013_filterselection_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterselection',
            name='agent_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filterselection',
            name='filename2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filterselection',
            name='organizer_signature',
            field=models.BooleanField(default=False),
        ),
    ]
