# Generated by Django 3.2.23 on 2024-01-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InspecciónAPI', '0014_auto_20231021_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policesubmissionlggs',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
