# Generated by Django 3.2.23 on 2024-01-24 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InspecciónAPI', '0015_alter_policesubmissionlggs_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintandofficetoattend',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file2return2doffice',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policecompliant',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trafficviolationcompared',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trafficviolationcomparedmycolission',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urbancontrol',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'is_organisor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
