# Generated by Django 3.2.23 on 2024-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0016_auto_20240124_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintandofficetoattend',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
        migrations.AddField(
            model_name='file2return2doffice',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
        migrations.AddField(
            model_name='policecompliant',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
        migrations.AddField(
            model_name='policesubmissionlggs',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
        migrations.AddField(
            model_name='trafficviolationcompared',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
        migrations.AddField(
            model_name='trafficviolationcomparedmycolission',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
        migrations.AddField(
            model_name='urbancontrol',
            name='insp_res',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
    ]
