# Generated by Django 3.2.23 on 2024-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspecciónAPI', '0018_auto_20240201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterselection',
            name='selected_complaintAndOfficeToAttend_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterselection',
            name='selected_file2Return2dOffice_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterselection',
            name='selected_policeSubmissionLGGS_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterselection',
            name='selected_police_compliant_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterselection',
            name='selected_trafficViolationComparedMyColission_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterselection',
            name='selected_trafficViolationCompared_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filterselection',
            name='selected_urban_control_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
