import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from contratacionAPI.models import ContratacionMain, processType, typologyType, resSecType, StateType

data = [
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-002-2023",
        "contractor": "SEBASTIAN MURILLO VANEGAS",
        "contractor_identification": "1041328460",
        "verification_digit": "4",
        "birthday_date": "1995-9-5",
        "blood_type": "B+",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión en el soporte técnico preventivo y correctivo de los equipos del área informática y los sistemas de información disponibles en las diferentes dependencias de la entidad para garantizar su adecuado funcionamiento y operación.",
        "worth": "14000000",
        "duration": "4 MESES",
        "contract_date": "2023-01-01",
        "start_date": "2023-01-17",
        "finish_date": "2023-05-16",
        "advance": "NO",
        "report_secop_begins": "2023-01-19",
        "secop_contract_report": "2023-01-19",
        "report_honest_antioquia": "2023-01-19",
        "report_institute_web": "2023-01-19",
        "sia_observe_report": "2023-02-24",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740058",
        "value_affected_bpin_proj_cdp": "14000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "Servicios para la comunidad, sociales y personales.",
        "item_value": "14000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "14000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-003-2023",
        "contractor": "CRISTIAN STIVEN MARIN OCAMPO",
        "contractor_identification": "1041325120",
        "verification_digit": "1",
        "birthday_date": "1988-4-15",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de los servicios de apoyo a la gestión administrativa en el trámite de los procesos contractuales de la entidad y la atención oportuna de requerimientos desde la Secretaria General y de Gobierno.",
        "worth": "11600000",
        "duration": "4 MESES",
        "contract_date": "2023-01-18",
        "start_date": "2023-01-18",
        "finish_date": "2023-05-17",
        "advance": "NO",
        "report_secop_begins": "2023-01-19",
        "secop_contract_report": "2023-01-19",
        "report_honest_antioquia": "2023-01-19",
        "report_institute_web": "2023-01-19",
        "sia_observe_report": "2023-02-24",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "11600000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "11600000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "11600000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-004-2023",
        "contractor": "SANTIAGO SUAREZ ARBELÁEZ",
        "contractor_identification": "1041324409",
        "verification_digit": "1",
        "birthday_date": "1986-12-19",
        "blood_type": "B-",
        "sex": "M",
        "object": "Prestación de los servicios de apoyo a la gestión administrativa en la revisión y control del cumplimiento de las normas urbanísticas en todo el territorio del municipio de San Vicente Ferrer",
        "worth": "12000000",
        "duration": "4 MESES",
        "contract_date": "2023-01-18",
        "start_date": "2023-01-18",
        "finish_date": "2023-05-17",
        "advance": "NO",
        "report_secop_begins": "2023-01-19",
        "secop_contract_report": "2023-01-19",
        "report_honest_antioquia": "2023-01-19",
        "report_institute_web": "2023-01-19",
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740012",
        "value_affected_bpin_proj_cdp": "12000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "Servicios para la comunidad, sociales y personales",
        "item_value": "12000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "SIGIFREDO HENAO GALLEGO",
        "observations": None,
        "contract_value_plus": "12000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-005-2023",
        "contractor": "DANIEL ESTEBAN MARIN SANCHEZ",
        "contractor_identification": "1007316320",
        "verification_digit": "6",
        "birthday_date": "2000-7-31",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de servicios apoyo en la operación y funcionamiento de los sistemas y cámaras de videovigilancia en el centro de monitoreo del Municipio de San Vicente Ferrer.",
        "worth": "8000000",
        "duration": "4 MESES",
        "contract_date": "2023-01-19",
        "start_date": "2023-01-19",
        "finish_date": "2023-05-18",
        "advance": "NO",
        "report_secop_begins": "2023-01-19",
        "secop_contract_report": "2023-01-19",
        "report_honest_antioquia": "2023-01-19",
        "report_institute_web": "2023-01-19",
        "sia_observe_report": "2023-02-24",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "8000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "8000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "8000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-006-2023",
        "contractor": "HECTOR HERNAN FERNANDEZ HENAO",
        "contractor_identification": "70287694",
        "verification_digit": "8",
        "birthday_date": "1969-4-20",
        "blood_type": "A+",
        "sex": "M",
        "object": "Prestación de servicios y de apoyo a la gestión, para la optimización y mejoramiento de los equipos tecnológicos instalados y al servicio de las diferentes dependencias de la administración municipal.",
        "worth": "8800000",
        "duration": "4 MESES",
        "contract_date": "2023-01-19",
        "start_date": "2023-01-19",
        "finish_date": "2023-05-18",
        "advance": "NO",
        "report_secop_begins": "2023-01-23",
        "secop_contract_report": "2023-01-23",
        "report_honest_antioquia": "2023-01-23",
        "report_institute_web": "2023-01-23",
        "sia_observe_report": "2023-02-27",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "8800000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "8800000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "8800000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-007-2023",
        "contractor": "RUBIELA DEL SOCORRO ARIAS CARVAJAL",
        "contractor_identification": "43419974",
        "verification_digit": "5",
        "birthday_date": "1965-12-1",
        "blood_type": "O+",
        "sex": "F",
        "object": "Prestación de servicios para la operación de un hogar de paso en la modalidad de familia, brindando atención y protección integral a los niños, niñas y adolescentes, que se encuentren vinculados en procesos administrativos de restablecimiento de derechos a cargo de la Comisaría de Familia.",
        "worth": "13340000",
        "duration": "11 MESES",
        "contract_date": "2023-01-24",
        "start_date": "2023-01-24",
        "finish_date": "2023-12-23",
        "advance": "NO",
        "report_secop_begins": "2023-01-27",
        "secop_contract_report": "2023-01-27",
        "report_honest_antioquia": "2023-01-27",
        "report_institute_web": "2023-01-27",
        "sia_observe_report": "2023-02-27",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740055",
        "value_affected_bpin_proj_cdp": "13340000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "13340000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "JHON FREDY JURADO GIRALDO",
        "observations": "N.A",
        "contract_value_plus": "13340000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-008-2023",
        "contractor": "LAURA CAMILA LEGUIZAMÓN GARZÓN",
        "contractor_identification": "1006874231",
        "verification_digit": "8",
        "birthday_date": "2000-08-17",
        "blood_type": "O+",
        "sex": "F",
        "object": "Prestación de servicios de apoyar a la Secretaría General y de Gobierno, a las Inspecciones Municipales de Policía y Tránsito y a la Comisaría de Familia del municipio, en las diferentes actuaciones de carácter jurisdiccional o administrativas, para contribuir a la descongestión de los despachos",
        "worth": "15750000",
        "duration": "10 MESES Y 15 DiAS",
        "contract_date": "2023-01-31",
        "start_date": "2023-01-02",
        "finish_date": "2023-12-15",
        "advance": "NO",
        "report_secop_begins": "2023-03-02",
        "secop_contract_report": "2023-02-27",
        "report_honest_antioquia": "2023-02-27",
        "report_institute_web": "2023-03-02",
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "15750000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "Servicios para la comunidad, sociales y personales",
        "item_value": "15750000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "MARÍA SOLEDAD SANTA ZAPATA",
        "observations": None,
        "contract_value_plus": "15750000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-009-2023",
        "contractor": "MARÍA NATALI ARBELÁEZ RESTREPO",
        "contractor_identification": "43221314",
        "verification_digit": "2",
        "birthday_date": "1985-08-25",
        "blood_type": "A+",
        "sex": "F",
        "object": "Prestación de servicios profesionales como abogada en la descongestión y trámite de los procesos que se adelanten en las Inspecciones Municipales a fin de aportar al mejoramiento de la convivencia, la seguridad ciudadana y la movilidad segura",
        "worth": "13600000",
        "duration": "4 MESES",
        "contract_date": "2023-02-07",
        "start_date": "2023-02-07",
        "finish_date": "2023-06-06",
        "advance": "NO",
        "report_secop_begins": "2023-02-08",
        "secop_contract_report": "2023-02-08",
        "report_honest_antioquia": "2023-02-09",
        "report_institute_web": "2023-02-09",
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "19200000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "Servicios para la comunidad, sociales y personales",
        "item_value": "19200000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "SIGIFREDO HENAO GALLEGO",
        "observations": None,
        "contract_value_plus": "13600000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-010-2023",
        "contractor": "ANA LIBIA LOPEZ SANCHEZ",
        "contractor_identification": "43420436",
        "verification_digit": "6",
        "birthday_date": "1969-4-27",
        "blood_type": "O+",
        "sex": "F",
        "object": "Prestación de los servicios de apoyo a la gestión administrativa en la adecuada implementación de la política de gestión documental y la actualización de los componentes y soportes de los procesos que conforman el Modelo Integrado de Planeación y Gestión.",
        "worth": "7700000",
        "duration": "3 MESES Y 15 DÍAS",
        "contract_date": "2023-02-16",
        "start_date": "2023-02-16",
        "finish_date": "2023-05-30",
        "advance": "NO",
        "report_secop_begins": "2023-02-22",
        "secop_contract_report": "2023-02-22",
        "report_honest_antioquia": "2023-02-22",
        "report_institute_web": "2023-03-01",
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "7700000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "7700000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "GLADYS JANETH CARDONA SANCHEZ",
        "observations": "N.A",
        "contract_value_plus": "7700000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-001-2023",
        "contractor": "DM MEDIOS AUDIOVISUALES S.A.S",
        "contractor_identification": "900728279",
        "verification_digit": "8",
        "birthday_date": "1976-5-9",
        "blood_type": "B+",
        "sex": "M",
        "object": "Apoyo logístico con el suministro de bienes y servicios para la realización del proceso de rendición de cuentas a la ciudadanía correspondiente a los avances de los programas y proyectos del plan de desarrollo de la vigencia 2022.",
        "worth": "20000000",
        "duration": "5 DIAS",
        "contract_date": "2023-02-18",
        "start_date": "2023-02-18",
        "finish_date": "2023-02-22",
        "advance": "NO",
        "report_secop_begins": "2023-02-14",
        "secop_contract_report": "2023-02-14",
        "report_honest_antioquia": "2023-02-14",
        "report_institute_web": "2023-02-14",
        "sia_observe_report": "2023-01-03",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "NO TIENE",
        "value_affected_bpin_proj_cdp": "20000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "20000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "20000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-011-2023",
        "contractor": "CASAL ASOCIADOS S.A.S. – FRANQUICIA COLMEDICOS RIONEGRO (JAVIER ALBERTO CASTRO GÓMEZ ).",
        "contractor_identification": "900321758",
        "verification_digit": "6",
        "birthday_date": "1956-7-14",
        "blood_type": "A+",
        "sex": "M",
        "object": "Prestación de los servicios profesionales para la realización de los siguientes exámenes médicos de ingreso, periódicos y/o de retiro, al personal de planta de la Administración Municipal de San Vicente Ferrer – Antioquia.",
        "worth": "5000000",
        "duration": "DEL 23 DE FEBRERO DE 2023 HASTA EL 31 DE DICIEMBRE DE 2023 HASTA AGOTAR EL PRESUPUESTO OFICIAL.",
        "contract_date": "2023-02-23",
        "start_date": "2023-02-23",
        "finish_date": "2023-12-31",
        "advance": "NO",
        "report_secop_begins": "2023-03-06",
        "secop_contract_report": "2023-03-06",
        "report_honest_antioquia": "2023-03-06",
        "report_institute_web": None,
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "NO TIENE",
        "value_affected_bpin_proj_cdp": "5000000",
        "budget_items": "2.1.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "5000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "GLADYS JANETH CARDONA SANCHEZ",
        "observations": "N.A",
        "contract_value_plus": "5000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-001-2023",
        "contractor": "CESAR AUGUSTO CARDONA CASTAÑO ",
        "contractor_identification": "70754071",
        "verification_digit": "3",
        "birthday_date": "1973-8-14",
        "blood_type": "O+",
        "sex": "M",
        "object": "Suministro de alimentación para personas privadas de la libertad que se encuentran sindicadas y que están ubicadas en la sala de reflexión del comando de policía mientras se realiza la legalización de captura y traslado a centro carcelario por orden judicial., de acuerdo a la siguiente descripción:",
        "worth": "30000000",
        "duration": "DEL 28 DE FEBRERO DE 2023 AL 31 DE DICIEMBRE DE 2023 O HASTA AGOTAR EL PRESUPUESTO OFICIAL",
        "contract_date": "2023-02-24",
        "start_date": "2023-02-28",
        "finish_date": "2023-12-31",
        "advance": "NO",
        "report_secop_begins": "2023-02-21",
        "secop_contract_report": "2023-03-02",
        "report_honest_antioquia": "2023-02-21",
        "report_institute_web": "2023-02-21",
        "sia_observe_report": "2023-02-03",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740052",
        "value_affected_bpin_proj_cdp": "30000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "30000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "30000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-012-2023",
        "contractor": "YURLADY MARÍN MARÍN",
        "contractor_identification": "43856865",
        "verification_digit": "4",
        "birthday_date": "1983-10-07",
        "blood_type": "O+",
        "sex": "F",
        "object": "Prestación de servicios de apoyo a la gestión administrativa en la identificación y caracterización de la población migrante asentada en la jurisdicción del municipio San Vicente Ferrer, además del apoyo a otras actividades que se adelanten desde la secretaria general y de Gobierno",
        "worth": "10000000",
        "duration": "5 MESES",
        "contract_date": "2023-03-08",
        "start_date": "2023-03-08",
        "finish_date": "2023-08-07",
        "advance": "NO",
        "report_secop_begins": "2023-03-08",
        "secop_contract_report": "2023-03-08",
        "report_honest_antioquia": "2023-03-08",
        "report_institute_web": "2023-03-08",
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740054",
        "value_affected_bpin_proj_cdp": "10000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "Servicios para la comunidad, sociales y personales",
        "item_value": "10000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "MARÍA SOLEDAD SANTA ZAPATA",
        "observations": None,
        "contract_value_plus": "10000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-003-2023",
        "contractor": "CESAR AUGUSTO CARDONA CASTAÑO ",
        "contractor_identification": "70754071",
        "verification_digit": "3",
        "birthday_date": "1973-8-14",
        "blood_type": "O+",
        "sex": "M",
        "object": "Suministro de alimentación para el personal de la fuerza pública (Policía, policía Judicial y Ejercito), en actividades de apoyo y refuerzo en la seguridad, orden público y convivencia ciudadana en el municipio de San Vicente Ferrer y suministro de alimentación con servicio de catering para las reuniones, eventos y/o actividades relacionadas con el cumplimiento de los objetivos y metas trazados en el plan de acción a partir de las reuniones y sesiones de los consejos, comités, juntas, mesas, entre otros y de las actividades con los servidores públicos de conformidad con la política de talento humano e integridad  ",
        "worth": "30000000",
        "duration": "HASTA EL 31  DE DICIEMBRE DE 2023",
        "contract_date": "2023-03-22",
        "start_date": "2023-03-24",
        "finish_date": "2023-12-31",
        "advance": "NO",
        "report_secop_begins": "2023-02-06",
        "secop_contract_report": "2023-02-06",
        "report_honest_antioquia": "2023-02-06",
        "report_institute_web": "2023-02-06",
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740052",
        "value_affected_bpin_proj_cdp": "30000000",
        "budget_items": "2.1.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "30000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "30000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-015-2023",
        "contractor": "PROSPECTIVA CONEXA S.A.S. (JORGE IVÁN SERNA GALLO).",
        "contractor_identification": "901,370,433",
        "verification_digit": "0",
        "birthday_date": "1978-1-22",
        "blood_type": "O-",
        "sex": "M",
        "object": "Prestación de servicios de transporte municipal e intermunicipal a funcionarios, agentes de Polic�a y reclusos de la estaci�n de polic�a a las audiencias, y dem�s, que se requieran en la Administraci�n Municipal cuando sea requerido.",
        "worth": "17000000",
        "duration": "Del 30 de marzo de 2023 hasta el 31 de diciembre de 2023 o hasta agotar el presupuesto oficial.",
        "contract_date": "2023-03-27",
        "start_date": "2023-03-30",
        "finish_date": "2023-12-31",
        "advance": "NO",
        "report_secop_begins": "2023-03-21",
        "secop_contract_report": "2023-03-31",
        "report_honest_antioquia": "2023-03-31",
        "report_institute_web": "2023-03-31",
        "sia_observe_report": "2023-03-31",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "NO APLICA",
        "value_affected_bpin_proj_cdp": "17000000",
        "budget_items": "2.1.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "17000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "17000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "CONVENIO DE ASOCIACIÓN",
        "contact_no": "C-A-SGG-001-2023",
        "contractor": "CONGREGACION DE RELIGIOSOS TERCIARIOS CAPUCHINOS DE NUESTRA SEÑORA DE LOS DOLORES (JACINTO IVÁN GUARÍN CARMONA).",
        "contractor_identification": "860005068",
        "verification_digit": "3",
        "birthday_date": "1958-3-3",
        "blood_type": "A+",
        "sex": "M",
        "object": "Realizar un proceso pedagógico-terapéutico a niños, niñas, adolescentes, estudiantes y usuarios en general que presentan uso y abuso de sustancias psicoactivas en aras a la revisión y resignificación de su proyecto de vida, desde la intervención individual, grupal, familiar como plataforma para su desarrollo bio-psico- social.",
        "worth": "28000000",
        "duration": "8 MESES",
        "contract_date": "2023-03-28",
        "start_date": "2023-03-28",
        "finish_date": "2023-11-27",
        "advance": "NO",
        "report_secop_begins": "2023-03-29",
        "secop_contract_report": "2023-03-29",
        "report_honest_antioquia": "2023-03-29",
        "report_institute_web": "2023-03-29",
        "sia_observe_report": "2023-03-29",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740055",
        "value_affected_bpin_proj_cdp": "28000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "28000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "28000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-013-2023",
        "contractor": "SEBASTIÁN QUINTERO MARÍN",
        "contractor_identification": "1041327123",
        "verification_digit": "2",
        "birthday_date": "1992-5-10",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de servicios profesionales para la realización de actividades pendientes para el cumplimiento de objetivos trazados del plan de desarrollo 2020 – 2023 de la Secretaría General y de Gobierno en la Administración Municipal de San Vicente Ferrer – Antioquia, consistente en los siguientes servicios:",
        "worth": "22000000",
        "duration": "3 MESES",
        "contract_date": "2023-03-29",
        "start_date": "2023-04-10",
        "finish_date": "2023-07-09",
        "advance": "NO",
        "report_secop_begins": "2023-03-29",
        "secop_contract_report": "2023-03-29",
        "report_honest_antioquia": "2023-03-29",
        "report_institute_web": "2023-03-29",
        "sia_observe_report": "2023-03-29",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740060",
        "value_affected_bpin_proj_cdp": "22000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "22000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "22000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-014-2023",
        "contractor": "RODOLFO ALBERTO MARTÍNEZ GUARÍN",
        "contractor_identification": "94427920",
        "verification_digit": "7",
        "birthday_date": "1975-3-24",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de servicios profesionales de asesoría jurídica a la Secretaria General y de Gobierno en el desarrollo de las actividades relacionadas con la finalización de los procesos administrativos tendientes a atender los requerimientos legales y de la comunidad en la solución efectiva de los asuntos sometidos a su consideración.",
        "worth": "13200000",
        "duration": "4 MESES",
        "contract_date": "2023-03-29",
        "start_date": "2023-03-29",
        "finish_date": "2023-07-28",
        "advance": "NO",
        "report_secop_begins": "2023-03-29",
        "secop_contract_report": "2023-03-29",
        "report_honest_antioquia": "2023-03-29",
        "report_institute_web": "2023-03-29",
        "sia_observe_report": "2023-03-29",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740061",
        "value_affected_bpin_proj_cdp": "13200000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "13200000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "13200000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "CONVENIO INTERADMINISTRATIVO",
        "contact_no": "C-INT-SGG-001-2023",
        "contractor": "MUNICIPIOS ASOCIADOS DEL ALTIPLANO DEL ORIENTE ANTIOQUEÑO MASORA (FABIO ANTONIO RIOS URREA)",
        "contractor_identification": "800183770",
        "verification_digit": "1",
        "birthday_date": "1979-3-3",
        "blood_type": "O+",
        "sex": "M",
        "object": "El objeto del presente convenio es: Aunar esfuerzos para el desarrollo y cumplimiento de las obligaciones municipales en desarrollo de la Ley de Infancia y Adolescencia, Ley 1098 de 2006, en especial, la atención y operación del Centro Transitorio para Adolescentes Infractores “CETRA”, en todas sus modalidades desde la atención inicial hasta la entrega a las autoridades y a las familias, además ofrecer transporte para su movilización en todo el proceso. ",
        "worth": "11440000",
        "duration": "Del 31 de marzo al 15 de diciembre de 2023, o hasta agotar el presupuesto oficial",
        "contract_date": "2023-03-31",
        "start_date": "2023-03-31",
        "finish_date": "2023-12-15",
        "advance": "NO",
        "report_secop_begins": "2023-04-12",
        "secop_contract_report": "2023-04-12",
        "report_honest_antioquia": "2023-04-12",
        "report_institute_web": "2023-04-12",
        "sia_observe_report": "2023-04-12",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740055",
        "value_affected_bpin_proj_cdp": "11440000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "13950000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "11440000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-004-2023",
        "contractor": "CESAR AUGUSTO CARDONA CASTAÑO ",
        "contractor_identification": "70754071",
        "verification_digit": "3",
        "birthday_date": "1973-8-14",
        "blood_type": "O+",
        "sex": "M",
        "object": "Suministro de alimentación para el personal de la fuerza pública (Policía, policía Judicial y Ejercito) y prestación de servicios de alojamiento para el personal policial que se encuentre en apoyo en actividades de apoyo y refuerzo en la seguridad, orden público y convivencia ciudadana en el Municipio de San Vicente Ferrer - Antioquia",
        "worth": "31453624",
        "duration": "Del 17 de mayo de 2023 al 31 de diciembre de 2023, o hasta agotar el presupuesto oficial.",
        "contract_date": "2023-05-15",
        "start_date": "2023-05-17",
        "finish_date": "2023-12-31",
        "advance": "NO",
        "report_secop_begins": "2023-05-09",
        "secop_contract_report": "2023-05-18",
        "report_honest_antioquia": "2023-05-09",
        "report_institute_web": "2023-05-09",
        "sia_observe_report": "2023-05-18",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740052",
        "value_affected_bpin_proj_cdp": "31453624",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "31453624",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "31453624",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "CONVENIO DE ASOCIACIÓN",
        "contact_no": "C-A-SGG-002-2023",
        "contractor": "ASOCIACIÓN DE CONCEJOS MUNICIPALES DEL ORIENTE ANTIOQUEÑO “ACORA”.  (CARLOS ANDRES ZULUAGA RIVILLAS).",
        "contractor_identification": "900112001",
        "verification_digit": "3",
        "birthday_date": "1990-9-10",
        "blood_type": "O+",
        "sex": "M",
        "object": "Aunar esfuerzos para la dignificación de la labor de los concejales en el territorio a partir de la realización de eventos y actividades a nivel local y regional, brindando conocimientos desde la coordinación, preparación logística hasta el reconocimiento de los valores que requiera la ejecución de las mismas.",
        "worth": "5000000",
        "duration": "UN (1) MES",
        "contract_date": "2023-05-19",
        "start_date": "2023-05-19",
        "finish_date": "2023-06-18",
        "advance": "NO",
        "report_secop_begins": "2023-05-25",
        "secop_contract_report": "2023-05-25",
        "report_honest_antioquia": "2023-05-25",
        "report_institute_web": "2023-05-25",
        "sia_observe_report": "2023-05-25",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "NO APLICA",
        "value_affected_bpin_proj_cdp": "5000000",
        "budget_items": "2.1.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "5000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "5000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-005-2023",
        "contractor": "PROSPECTIVA CONEXA S.A.S.(JORGE IVÁN SERNA GALLO).",
        "contractor_identification": "901370433",
        "verification_digit": "0",
        "birthday_date": "1978-1-22",
        "blood_type": "O-",
        "sex": "M",
        "object": "Suministro de bienes, servicios y apoyo logístico, para el desarrollo de las actividades dirigidas desde la Comisaría de Familia el plan de acción de la mesa de participación efectiva de las víctimas del Municipio de San Vicente Ferrer adscritas a la Secretaría General y de Gobierno dando así cumplimiento con el plan de trabajo de 2023 contemplado en el plan de desarrollo 2020-2023, de acuerdo con la propuesta presentada por el contratista.",
        "worth": "26000000",
        "duration": "CINCO (5) MESES o hasta agotar el presupuesto, contados a partir del 26-05-2023.",
        "contract_date": "2023-05-26",
        "start_date": "2023-05-30",
        "finish_date": "2023-10-29",
        "advance": "NO",
        "report_secop_begins": "2023-05-23",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-05-24",
        "report_institute_web": "2023-05-24",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740055",
        "value_affected_bpin_proj_cdp": "19,000,000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "26000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "26000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": None,
        "typology": None,
        "contact_no": None,
        "contractor": None,
        "contractor_identification": None,
        "verification_digit": None,
        "birthday_date": None,
        "blood_type": None,
        "sex": None,
        "object": None,
        "VALOR ": None,
        "duration": None,
        "contract_date": None,
        "start_date": None,
        "finish_date": None,
        "advance": None,
        "report_secop_begins": None,
        "secop_contract_report": None,
        "report_honest_antioquia": None,
        "report_institute_web": None,
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740059",
        "value_affected_bpin_proj_cdp": "7000000",
        "budget_items": None,
        "article_name": None,
        "item_value": None,
        "state": None,
        "responsible_secretary": None,
        "name_supervisor_or_controller": None,
        "observations": None,
        "contract_value_plus": None,
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-006-2023",
        "contractor": "SEBASTIAN MURILLO VANEGAS",
        "contractor_identification": "1041328460",
        "verification_digit": "4",
        "birthday_date": "1995-9-5",
        "blood_type": "B+",
        "sex": "M",
        "object": "Contratar el desarrollo de un SOFTWARE para la Secretaria General y de Gobierno, para optimizar los tramites internos de PQRS, contratación e inspección de Policía 3 a 6 categoría uno y dos y la Inspección de Policía 3 a 6 categoría con énfasis en control urbanístico.",
        "worth": "31800000",
        "duration": "OCHO (8) DÍAS",
        "contract_date": "2023-05-30",
        "start_date": "2023-05-30",
        "finish_date": "2023-06-07",
        "advance": "NO",
        "report_secop_begins": "2023-05-24",
        "secop_contract_report": "2023-05-31",
        "report_honest_antioquia": "2023-05-31",
        "report_institute_web": "2023-05-24",
        "sia_observe_report": "2023-05-31",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740058",
        "value_affected_bpin_proj_cdp": "32000000",
        "budget_items": "2.1.2.01.01.003.03.02",
        "article_name": "Paquetes de software",
        "item_value": "32000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "31800000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-016-2023",
        "contractor": "DANIEL ESTEBAN MARIN SANCHEZ",
        "contractor_identification": "1007316320",
        "verification_digit": "6",
        "birthday_date": "2000-7-31",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión en el seguimiento y control de las cámaras instaladas en espacio público conectadas al sistema de video vigilancia, las cuales se visualizan desde el centro de monitoreo como soporte fundamental de la seguridad, el orden público, la convivencia y la tranquilidad ciudadana en el municipio San Vicente Ferrer",
        "worth": "12000000",
        "duration": "SEIS (6) MESES",
        "contract_date": "2023-01-06",
        "start_date": "2023-01-06",
        "finish_date": "2023-11-30",
        "advance": "NO",
        "report_secop_begins": "2023-01-06",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-01-06",
        "report_institute_web": "2023-01-06",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "12000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "12000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "12000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-017-2023",
        "contractor": "CRISTIAN STIVEN MARIN OCAMPO",
        "contractor_identification": "1041325120",
        "verification_digit": "1",
        "birthday_date": "1988-4-15",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión en la revisión y actualización de los instrumentos para establecer lineamientos tendientes a cumplir con los parámetros normativos y procedimentales, apoyo a la elaboración y revisión de documentos contractuales requeridos en las diferentes secretarías para dar cumplimiento a los planes, programas y proyectos contemplados en el plan de acción de la vigencia 2023.",
        "worth": "17400000",
        "duration": "SEIS (6) MESES",
        "contract_date": "2024-06-01",
        "start_date": "2023-01-06",
        "finish_date": "2023-11-30",
        "advance": "NO",
        "report_secop_begins": "2023-01-06",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-01-06",
        "report_institute_web": "2023-01-06",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": "2023-01-06",
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "11400000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "17400000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "17400000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": None,
        "typology": None,
        "contact_no": None,
        "contractor": None,
        "contractor_identification": None,
        "verification_digit": None,
        "birthday_date": None,
        "blood_type": None,
        "sex": None,
        "object": None,
        "worth": None,
        "duration": None,
        "contract_date": None,
        "start_date": None,
        "finish_date": None,
        "advance": None,
        "report_secop_begins": "2023-01-06",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-01-06",
        "report_institute_web": "2023-01-06",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": "2023-01-06",
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "6000000",
        "budget_items": None,
        "article_name": None,
        "item_value": None,
        "state": None,
        "responsible_secretary": None,
        "name_supervisor_or_controller": None,
        "observations": None,
        "contract_value_plus": None,
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-018-2023",
        "contractor": "SEBASTIAN MURILLO VANEGAS",
        "contractor_identification": "1041328460",
        "verification_digit": "4",
        "birthday_date": "1995-9-5",
        "blood_type": "B+",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión en el soporte técnico de sistemas operativos y servidores y redes de datos. Entendiéndose por atención a consultas de usuarios, la instalación, configuración, actualización y administración de los sistemas informáticos incluyendo tanto el software como el hardware, tanto en servidores como en los equipos de los puestos de trabajo físicos o virtualizados y escritorios de usuario, así como en otro tipo de dispositivos, para el correcto funcionamiento de la infraestructura informática de la administración municipal de San Vicente Ferrer.",
        "worth": "21000000",
        "duration": "SEIS (6) MESES",
        "contract_date": "2025-06-01",
        "start_date": "2023-01-06",
        "finish_date": "2023-11-30",
        "advance": "NO",
        "report_secop_begins": "2023-01-06",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-01-06",
        "report_institute_web": "2023-01-06",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": "2023-01-06",
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740058",
        "value_affected_bpin_proj_cdp": "17500000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "21000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "21000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": None,
        "typology": None,
        "contact_no": None,
        "contractor": None,
        "contractor_identification": None,
        "verification_digit": None,
        "birthday_date": None,
        "blood_type": None,
        "sex": None,
        "object": None,
        "worth": None,
        "duration": None,
        "contract_date": None,
        "start_date": None,
        "finish_date": None,
        "advance": None,
        "report_secop_begins": "2023-01-06",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-01-06",
        "report_institute_web": "2023-01-06",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": "2023-01-06",
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "3500000",
        "budget_items": None,
        "article_name": None,
        "item_value": None,
        "state": None,
        "responsible_secretary": None,
        "name_supervisor_or_controller": None,
        "observations": None,
        "contract_value_plus": None,
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-019-2023",
        "contractor": "JUAN DAVID CÓRDOBA HERNÁNDEZ",
        "contractor_identification": "1036639607",
        "verification_digit": "6",
        "birthday_date": "1992-3-26",
        "blood_type": "O+",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión con la asesoría, apoyo y acompañamiento en el trámite de los procesos administrativos relacionados con el cumplimiento de la normatividad relativa al régimen pensional, el pasivo pensional del municipio San Vicente Ferrer.",
        "worth": "15600000",
        "duration": "SEIS (6) MESES",
        "contract_date": "2026-06-01",
        "start_date": "2023-01-06",
        "finish_date": "2023-11-30",
        "advance": "NO",
        "report_secop_begins": "2023-01-06",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-01-06",
        "report_institute_web": "2023-01-06",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": "2023-01-06",
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740056",
        "value_affected_bpin_proj_cdp": "15600000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "15600000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "15600000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-007-2023",
        "contractor": "SEBASTIAN MURILLO VANEGAS",
        "contractor_identification": "1041328460",
        "verification_digit": "4",
        "birthday_date": "1995-9-5",
        "blood_type": "B+",
        "sex": "M",
        "object": "Ejecutar las labores de mantenimiento preventivo y/o correctivo de las impresoras, escáner, equipos de cómputo y otros accesorios hasta dejarlos en óptimas condiciones para el uso de los servidores públicos en beneficio de la oportuna y continua prestación de los servicios a los usuarios de la administración municipal de San Vicente Ferrer, Antioquia, de acuerdo a la propuesta presentada por el contratista",
        "worth": "32000000",
        "duration": "QUINCE (15) DÍAS",
        "contract_date": "2023-05-30",
        "start_date": "2023-05-30",
        "finish_date": "2023-06-21",
        "advance": "NO",
        "report_secop_begins": "2023-05-24",
        "secop_contract_report": "2023-01-06",
        "report_honest_antioquia": "2023-05-24",
        "report_institute_web": "2023-05-24",
        "sia_observe_report": "2023-01-06",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740058",
        "value_affected_bpin_proj_cdp": "32000000",
        "budget_items": "2.1.2.01.01.003.03.02",
        "article_name": "Maquinaria de informática y sus partes, piezas y accesorios,",
        "item_value": "31800000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "31800000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-008-2023",
        "contractor": "SEBASTIAN MURILLO VANEGAS",
        "contractor_identification": "1041328460",
        "verification_digit": "4",
        "birthday_date": "1995-9-5",
        "blood_type": "B+",
        "sex": "M",
        "object": "Suministro de bienes requeridos por la policía judicial con jurisdicción en el municipio San Vicente Ferrer, de conformidad con el proyecto presentado y aprobado por el Comité Territorial de Orden Público del municipio de San Vicente Ferrer, Antioquia, de acuerdo con la propuesta presentada por el contratista.",
        "worth": "25000000",
        "duration": "10 DIAS",
        "contract_date": "2023-06-08",
        "start_date": "2023-06-08",
        "finish_date": "2023-06-17",
        "advance": "NO",
        "report_secop_begins": "2023-06-05",
        "secop_contract_report": "2023-06-09",
        "report_honest_antioquia": "2023-06-05",
        "report_institute_web": "2023-06-05",
        "sia_observe_report": "2023-06-09",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740052",
        "value_affected_bpin_proj_cdp": "25000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "25000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "25000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-020-2023",
        "contractor": "SANTIAGO SUAREZ ARBELÁEZ",
        "contractor_identification": "1041324409",
        "verification_digit": "1",
        "birthday_date": "1986-12-19",
        "blood_type": "B-",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión en labores de vigilancia y control sobre las obras que conllevan al desarrollo e intervención del territorio en San Vicente Ferrer, a fin de asegurar que cumplan con la normatividad y los procedimientos establecidos desde la Oficina de Ordenamiento Territorial",
        "worth": "15000000",
        "duration": "CINCO (5) MESES",
        "contract_date": "2023-06-08",
        "start_date": "2023-06-08",
        "finish_date": "2023-11-07",
        "advance": "NO",
        "report_secop_begins": "2023-06-09",
        "secop_contract_report": "2023-06-09",
        "report_honest_antioquia": "2023-06-09",
        "report_institute_web": "2023-06-09",
        "sia_observe_report": "2023-06-09",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740012",
        "value_affected_bpin_proj_cdp": "15000000",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "15000000",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "15000000",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN DIRECTA",
        "typology": "PRESTACIÓN DE SERVICIOS",
        "contact_no": "C-PS-SGG-021-2023",
        "contractor": "OSCAR FERNÁN MARÍN ECHEVERRY",
        "contractor_identification": "70289924",
        "verification_digit": "6",
        "birthday_date": "1980-6-12",
        "blood_type": "A+",
        "sex": "M",
        "object": "Prestación de servicios de apoyo a la gestión brindando información y/o capacitación a la comunidad en general sobre con la socialización de la ley 1801 de 2016, con énfasis en la prevención de las conductas contrarias a la convivencia en el municipio San Vicente Ferrer, de conformidad con los lineamientos de la Guía para socializar la Ley 1801 Código Nacional de Policía y Convivencia a la comunidad expedida desde la Dirección de la Policía Nacional.",
        "worth": "17432150",
        "duration": "TRES (3) MESES",
        "contract_date": "2023-06-14",
        "start_date": "2023-06-14",
        "finish_date": "2023-09-13",
        "advance": "NO",
        "report_secop_begins": "2023-06-15",
        "secop_contract_report": "2023-06-15",
        "report_honest_antioquia": "2023-06-15",
        "report_institute_web": "2023-06-15",
        "sia_observe_report": "2023-06-15",
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740052",
        "value_affected_bpin_proj_cdp": "17432150",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "17432150",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "17432150",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": "CONTRATACIÓN MÍNIMA CUANTÍA.",
        "typology": "SUMINISTRO",
        "contact_no": "C-S-SGG-009-2023",
        "contractor": "SEBASTIAN MURILLO VANEGAS",
        "contractor_identification": "1041328460",
        "verification_digit": "4",
        "birthday_date": "1995-9-5",
        "blood_type": "B+",
        "sex": "M",
        "object": "Suministro de bienes requeridos por la Policía Nacional con asiento en la Estación Local para la implementación y puesta en funcionamiento de la sala de mediación policial, de conformidad con lo contemplado en la ley 1801 de 2016.",
        "worth": "19319800",
        "duration": "DIEZ (10) DÍAS",
        "contract_date": "2023-06-20",
        "start_date": "2023-06-21",
        "finish_date": "2023-06-30",
        "advance": "NO",
        "report_secop_begins": None,
        "secop_contract_report": None,
        "report_honest_antioquia": None,
        "report_institute_web": None,
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": "NO",
        "value_added": "NO",
        "extra_time": "NO",
        "bpin_project_code": "2022056740052",
        "value_affected_bpin_proj_cdp": "19526791",
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "14526761",
        "state": "EJECUCION",
        "responsible_secretary": "SECRETARÍA GENERAL Y DE GOBIERNO",
        "name_supervisor_or_controller": "ROSMIRA MURILLO HENAO",
        "observations": "N.A",
        "contract_value_plus": "19319800",
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    },
    {
        "process": None,
        "typology": None,
        "contact_no": None,
        "contractor": None,
        "contractor_identification": None,
        "verification_digit": None,
        "birthday_date": None,
        "blood_type": None,
        "sex": None,
        "object": None,
        "worth": None,
        "duration": None,
        "contract_date": None,
        "start_date": None,
        "finish_date": None,
        "advance": None,
        "report_secop_begins": None,
        "secop_contract_report": None,
        "report_honest_antioquia": None,
        "report_institute_web": None,
        "sia_observe_report": None,
        "act_liquidation": None,
        "settlement_report": None,
        "close_record_and_report_date": None,
        "addition": None,
        "value_added": None,
        "extra_time": None,
        "bpin_project_code": None,
        "value_affected_bpin_proj_cdp": None,
        "budget_items": "2.3.2.02.02.009",
        "article_name": "SERVICIOS PARA LA COMUNIDAD SOCIALES Y PERSONALES",
        "item_value": "5000000",
        "state": None,
        "responsible_secretary": None,
        "name_supervisor_or_controller": None,
        "observations": None,
        "contract_value_plus": None,
        "real_executed_value_according_to_settlement": None,
        "file_status": None
    }
]


for item in data:

    process = processType.objects.create(name=item['process'])
    typology = typologyType.objects.create(name=item['typology'])
    contact_no = item.get('contact_no', '')
    contractor = item.get('contractor', '')
    contractor_identification = item.get('contractor_identification', '')
    verification_digit = item.get('verification_digit', '')
    birthday_date = item.get('birthday_date', '')
    blood_type = item.get('blood_type', '')
    sex = item.get('sex', '')
    object = item.get('object', '')
    worth = item.get('worth', '')
    duration = item.get('duration', '')
    contract_date = item.get('contract_date', '')
    start_date = item.get('start_date', '')
    finish_date = item.get('finish_date', '')
    advance = item.get('advance', '')
    report_secop_begins = item.get('report_secop_begins', '')
    secop_contract_report = item.get('secop_contract_report', '')
    report_honest_antioquia = item.get('report_honest_antioquia', '')
    report_institute_web = item.get('report_institute_web', '')
    sia_observe_report = item.get('sia_observe_report', '')
    act_liquidation = item.get('act_liquidation', '')
    settlement_report = item.get('settlement_report', '')
    close_record_and_report_date = item.get('close_record_and_report_date', '')
    addition = item.get('addition', '')
    value_added = item.get('value_added', '')
    extra_time = item.get('extra_time', '')
    bpin_project_code = item.get('bpin_project_code', '')
    value_affected_bpin_proj_cdp = item.get('value_affected_bpin_proj_cdp', '')
    budget_items = item.get('budget_items', '')
    article_name = item.get('article_name', '')
    item_value = item.get('item_value', '')
    state = StateType.objects.create(name=item['state'])
    responsible_secretary = resSecType.objects.create(name=item['responsible_secretary'])
    name_supervisor_or_controller = item.get('name_supervisor_or_controller', '')
    observations = item.get('observations', '')
    contract_value_plus = item.get('contract_value_plus', '')
    real_executed_value_according_to_settlement = item.get('real_executed_value_according_to_settlement', '')
    file_status = item.get('file_status', '')    
    

    ContratacionMain.objects.create(
        process = process,
        typology = typology,
        contact_no = contact_no,
        contractor = contractor,
        contractor_identification = contractor_identification,
        verification_digit = verification_digit,
        birthday_date = birthday_date,
        blood_type = blood_type,
        sex = sex,
        object = object,
        worth = worth,
        duration = duration,
        contract_date = contract_date,
        start_date = start_date,
        finish_date = finish_date,
        advance = advance,
        report_secop_begins = report_secop_begins,
        secop_contract_report = secop_contract_report,
        report_honest_antioquia = report_honest_antioquia,
        report_institute_web = report_institute_web,
        sia_observe_report = sia_observe_report,
        act_liquidation = act_liquidation,
        settlement_report = settlement_report,
        close_record_and_report_date = close_record_and_report_date,
        addition = addition,
        value_added = value_added,
        extra_time = extra_time,
        bpin_project_code = bpin_project_code,
        value_affected_bpin_proj_cdp = value_affected_bpin_proj_cdp,
        budget_items = budget_items,
        article_name = article_name,
        item_value = item_value,
        state = state,
        responsible_secretary = responsible_secretary,
        name_supervisor_or_controller = name_supervisor_or_controller,
        observations = observations,
        contract_value_plus = contract_value_plus,
        real_executed_value_according_to_settlement = real_executed_value_according_to_settlement,
        file_status = file_status
    )
    
    print("Succssfully Seeded the data")