NAMES  = [
'Estudios previos (Lo expide el municipio) y anexos.', 
'Estudios',
'Experiencia Laboral  ',
'Conocimientos adicionales  ',
'Certificado de no existencia de personal.',
'Disponibilidad presupuestal (Lo expide el municipio).',
'Propuesta del servicio a prestar (RE – ODC – 003)',
'Copia de la cédula de la persona natural o representante legal de la entidad.',
'Copia del RUT de la persona natural o representante legal de la entidad.',
'Hoja de vida SIGEP, para personas naturales y Hoja de Vida de la Función Pública para personas jurídicas.',
'Formato de Declaración de bienes y rentas SIGEP para personas naturales (o declaración de rentas para personas jurídicas). ',
'Certificado de antecedentes fiscales de la persona natural o del representante legal de la entidad, expedido por la Contraloría General de la República.',
'Certificado de antecedentes disciplinarios de la persona natural o del representante legal de la entidad, expedido por la Procuraduría. ',
'Certificado de antecedentes judiciales de la persona natural o del representante legal de la entidad, expedido por la Policía. ',
'Certificado Registro Nacional de Medidas Correctivas de la persona natural o del representante legal de la entidad.',
'Consulta de inhabilidades por delitos sexuales cometidos contra menores de 18 años. Ley 1918 de 2018.',
'Declaración de conflicto de interés para contratista.',
'Certificado de Cámara de Comercio o personería jurídica.',
'Certificado de afiliación a salud, pensiones y ARL. ',
'Documentos para afiliación a seguridad social (de acuerdo a los beneficiarios).',
'Licencia de conducción vigente (Si se requiere para el desarrollo de la actividad contractual).',
'Certificado de paz y salvo por pago de aportes parafiscales y seguridad social y planillas de pago (persona jurídica), adjuntando copia de la Tarjeta Profesional  y cédula si es expedido por Contador Público.',
'Certificado médico ocupacional para prestación de servicios profesionales y de apoyo a la gestión, obligatorio, el cual es asumido por el contratista (Decreto 1072 de 2015 articulo 2.2.4.2.2.18), el cual tiene una vigencia de tres años a excepción de los contratistas o trabajadores que hayan reportado accidentes de trabajo en el último año. *Para las actividades que lo requieran certificado para trabajar en alturas.',
'Paz y salvo municipal ',
'Situación militar definida para hombres menores de 50 años.',
'Documentos de vehículos (SOAT, RTM, licencia de tránsito, licencia de conducción), solo para transporte.',
'Garantía de cumplimiento '
]