# Generated by Django 3.2.23 on 2024-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255)),
                ('conservation', models.BooleanField(default=False)),
                ('personal_services', models.BooleanField(default=False)),
                ('work_contract', models.BooleanField(default=False)),
                ('direct_contract', models.BooleanField(default=False)),
                ('fulfills', models.CharField(max_length=255)),
            ],
        ),
    ]
