# Generated by Django 3.2.19 on 2023-12-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_ticketuseragent'),
        ('ticketAPI', '0005_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assign_to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.ticketuseragent'),
        ),
    ]
