# Generated by Django 3.2.19 on 2023-12-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketAPI', '0008_ticket_ticket_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_num',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
