# Generated by Django 3.2.19 on 2023-12-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketAPI', '0009_alter_ticket_ticket_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_num',
        ),
    ]
