# Generated by Django 3.2.19 on 2023-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketAPI', '0010_remove_ticket_ticket_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
