# Generated by Django 3.2.19 on 2023-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketAPI', '0011_alter_ticket_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
