# Generated by Django 3.2.19 on 2023-12-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketAPI', '0012_auto_20231210_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_num',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
