# Generated by Django 3.2.19 on 2023-06-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acroymsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=310)),
            ],
        ),
        migrations.CreateModel(
            name='processType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=310)),
            ],
        ),
        migrations.CreateModel(
            name='resSecType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=310)),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=310)),
            ],
        ),
        migrations.CreateModel(
            name='typologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=310)),
            ],
        ),
        migrations.CreateModel(
            name='ContratacionMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=2300, null=True)),
                ('contractor', models.CharField(max_length=2300, null=True)),
                ('contractor_identification', models.CharField(max_length=2300, null=True)),
                ('verification_digit', models.CharField(max_length=2300, null=True)),
                ('birthday_date', models.DateTimeField()),
                ('blood_type', models.CharField(max_length=2300, null=True)),
                ('sex', models.CharField(max_length=2300, null=True)),
                ('object', models.CharField(max_length=2300, null=True)),
                ('worth', models.CharField(max_length=2300, null=True)),
                ('duration', models.CharField(max_length=2300, null=True)),
                ('contract_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('advance', models.CharField(max_length=2310)),
                ('report_secop_begins', models.CharField(max_length=2310)),
                ('secop_contract_report', models.CharField(max_length=2310)),
                ('report_honest_antioquia', models.CharField(max_length=2310)),
                ('report_institute_web', models.CharField(max_length=2310)),
                ('sia_observe_report', models.CharField(max_length=2310)),
                ('act_liquidation', models.CharField(max_length=2310)),
                ('settlement_report', models.CharField(max_length=2310)),
                ('close_record_and_report_date', models.CharField(max_length=2310)),
                ('addition', models.CharField(max_length=2310)),
                ('value_added', models.CharField(max_length=2310)),
                ('extra_time', models.CharField(max_length=2310)),
                ('bpin_project_code', models.CharField(max_length=2310)),
                ('value_affected_bpin_proj_cdp', models.CharField(max_length=2310)),
                ('budget_items', models.CharField(max_length=2310)),
                ('article_name', models.CharField(max_length=2310)),
                ('item_value', models.CharField(max_length=2310)),
                ('name_supervisor_or_controller', models.CharField(max_length=2310)),
                ('observations', models.CharField(max_length=2310)),
                ('contract_value_plus', models.CharField(max_length=2310)),
                ('real_executed_value_according_to_settlement', models.CharField(max_length=2310)),
                ('file_status', models.CharField(max_length=2310)),
                ('acroyms_of_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.acroymstype')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.processtype')),
                ('responsible_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.ressectype')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.statetype')),
                ('typology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.typologytype')),
            ],
        ),
    ]
