# Generated by Django 3.2.19 on 2023-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratacionmain',
            old_name='close_record_and_report_date',
            new_name='close_record',
        ),
        migrations.AddField(
            model_name='contratacionmain',
            name='report_date',
            field=models.CharField(blank=True, max_length=2310, null=True),
        ),
    ]
