# Generated by Django 3.2.19 on 2023-07-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0002_auto_20230728_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionmain',
            name='close_record',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratacionmain',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratacionmain',
            name='settlement_report',
            field=models.DateField(blank=True, null=True),
        ),
    ]
