# Generated by Django 3.2.19 on 2023-08-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0004_auto_20230728_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratacionmain',
            old_name='sia_observe_report',
            new_name='sia_observe_report',
        ),
    ]
