# Generated by Django 3.2.19 on 2023-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0005_alter_valueadded_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionmain',
            name='value_added',
            field=models.ManyToManyField(to='contratacionAPI.ValueAdded'),
        ),
    ]
