# Generated by Django 3.2.23 on 2024-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0008_lawfirmmodel_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirmmodel',
            name='document',
            field=models.TextField(),
        ),
    ]
