# Generated by Django 3.2.23 on 2024-01-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0009_alter_lawfirmmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirmmodel',
            name='conservation',
            field=models.CharField(max_length=255),
        ),
    ]
