# Generated by Django 3.2.23 on 2024-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0010_alter_lawfirmmodel_conservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousStudyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_receive_mail', models.DateField()),
                ('process', models.CharField(max_length=255)),
                ('responsible_secretary', models.CharField(max_length=255)),
                ('purpose_of_activities', models.TextField()),
                ('worth', models.IntegerField()),
                ('term', models.IntegerField()),
                ('bpin_code', models.IntegerField()),
                ('lawyer_role', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
