# Generated by Django 3.2.23 on 2024-01-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0011_previousstudymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousstudymodel',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.processtype'),
        ),
        migrations.AlterField(
            model_name='previousstudymodel',
            name='responsible_secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.ressectype'),
        ),
    ]
