# Generated by Django 3.2.23 on 2024-01-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0012_auto_20240124_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviousStudyModel',
        ),
    ]
