# Generated by Django 3.2.23 on 2024-02-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0013_delete_previousstudymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionmain',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
