# Generated by Django 3.2.23 on 2024-02-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0014_contratacionmain_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratacionmain',
            name='report_honest_antioquia',
        ),
    ]
