# Generated by Django 3.2.23 on 2024-02-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0015_remove_contratacionmain_report_honest_antioquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionmain',
            name='program',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
    ]
