# Generated by Django 3.2.23 on 2024-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0016_contratacionmain_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contratacionmain',
            name='source_of_resources',
            field=models.ManyToManyField(to='contratacionAPI.SourceOfResources'),
        ),
    ]
