# Generated by Django 3.2.23 on 2024-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0018_contratacionmain_bpin_proj_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpinProjName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='contratacionmain',
            name='bpin_proj_name',
        ),
        migrations.AddField(
            model_name='contratacionmain',
            name='bpin_proj_name',
            field=models.ManyToManyField(to='contratacionAPI.BpinProjName'),
        ),
    ]
