# Generated by Django 3.2.23 on 2024-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0019_auto_20240304_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpinprojname',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
