# Generated by Django 3.2.23 on 2024-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacionAPI', '0020_alter_bpinprojname_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contratacionmain',
            name='expense_type',
            field=models.CharField(blank=True, max_length=2310, null=True),
        ),
        migrations.AddField(
            model_name='contratacionmain',
            name='service_segment',
            field=models.ManyToManyField(to='contratacionAPI.ServiceSegment'),
        ),
    ]
