# Generated by Django 3.2.19 on 2023-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SisbenMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_card', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
