# Generated by Django 3.2.19 on 2023-09-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisbenAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisbenmain',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sisbenmain',
            name='citizenship_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sisbenmain',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
