# Generated by Django 3.2.19 on 2023-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisbenAPI', '0003_auto_20230930_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisbenmain',
            name='doc_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sisbenmain',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sisbenmain',
            name='sex',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
