# Generated by Django 3.2.19 on 2023-09-20 14:08

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=Auth.models.uploadSignature_to, verbose_name='Image'),
        ),
    ]
