# Generated by Django 3.2.19 on 2023-11-15 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_user_is_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('update', 'update'), ('create', 'create'), ('delete', 'delete'), ('empty', 'empty')], default='empty', max_length=20)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
