# Generated by Django 3.2.19 on 2023-11-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_activitytracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytracker',
            name='sector',
            field=models.CharField(choices=[('pqrs', 'pqrs'), ('inspect', 'inspect'), ('hiring', 'hiring'), ('sisben', 'sisben'), ('empty', 'empty')], default='empty', max_length=20),
        ),
    ]
