# Generated by Django 3.2.19 on 2023-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_activitytracker_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
