# Generated by Django 3.2.19 on 2023-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_ticketuseragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ticket_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ticket_agent',
            field=models.BooleanField(default=False),
        ),
    ]
