# Generated by Django 3.2.19 on 2023-12-09 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_auto_20231206_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketuseragent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
