# Generated by Django 3.2.23 on 2024-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_alter_ticketuseragent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
