# Generated by Django 3.2.23 on 2024-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_user_is_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent_org',
            field=models.BooleanField(default=False),
        ),
    ]
