# Generated by Django 3.2.19 on 2023-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsNotifify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1000)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
