# Generated by Django 3.2.19 on 2023-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0002_fileresnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsmain',
            name='sender',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
