# Generated by Django 3.2.23 on 2024-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0002_pqrsnotifify'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsFileNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=310)),
            ],
        ),
    ]
