# Generated by Django 3.2.19 on 2023-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0002_auto_20230613_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsmain',
            name='file_res',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
