# Generated by Django 3.2.23 on 2024-01-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0003_pqrsfilenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsmain',
            name='date_of_entry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pqrsmain',
            name='date_of_response',
            field=models.DateField(auto_now_add=True),
        ),
    ]
