# Generated by Django 3.2.19 on 2023-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0003_alter_pqrsmain_file_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsmain',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
