# Generated by Django 3.2.19 on 2023-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0003_alter_pqrsmain_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsmain',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/File2Return2dOffice/'),
        ),
    ]
