# Generated by Django 3.2.23 on 2024-01-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0006_alter_pqrsmain_date_of_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsmain',
            name='date_of_response',
            field=models.DateField(blank=True, null=True),
        ),
    ]
