# Generated by Django 3.2.23 on 2024-01-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0007_alter_pqrsmain_date_of_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrsmain',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
