# Generated by Django 3.2.23 on 2024-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsAPI', '0008_alter_pqrsmain_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsmain',
            name='pdf_res',
            field=models.FileField(blank=True, null=True, upload_to='pdf/pqrs_res/'),
        ),
    ]
