# Generated by Django 3.2.23 on 2024-01-24 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacionAPI', '0013_delete_previousstudymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousStudyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_receive_mail', models.DateField()),
                ('purpose_of_activities', models.TextField()),
                ('worth', models.IntegerField()),
                ('term', models.IntegerField()),
                ('bpin_code', models.IntegerField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/lawyer/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lawyer_role', models.ForeignKey(blank=True, limit_choices_to={'is_lawyer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.processtype')),
                ('responsible_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacionAPI.ressectype')),
            ],
        ),
    ]
