# Generated by Django 3.2.23 on 2024-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawAPI', '0002_alter_previousstudymodel_bpin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(blank=True, max_length=2300, null=True)),
                ('headquarter', models.CharField(blank=True, max_length=2300, null=True)),
                ('area_of_operation', models.CharField(blank=True, max_length=2300, null=True)),
                ('v_class', models.CharField(blank=True, max_length=2300, null=True)),
                ('v_make', models.CharField(blank=True, max_length=2300, null=True)),
                ('v_model', models.CharField(blank=True, max_length=2300, null=True)),
                ('v_license_plate', models.CharField(blank=True, max_length=2300, null=True)),
                ('v_cylinder_capacity', models.CharField(blank=True, max_length=2300, null=True)),
                ('v_fuel_type', models.CharField(blank=True, max_length=2300, null=True)),
                ('service_level', models.CharField(blank=True, max_length=2300, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=2300, null=True)),
                ('consecutive_numbering', models.CharField(blank=True, max_length=2300, null=True)),
            ],
        ),
    ]
