# Generated by Django 3.2.23 on 2024-05-02 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawAPI', '0004_operationmodel_authorize_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmodel',
            name='authorize_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
